### ISSUE TITLE
Add Instagram Service Integration 

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#22] opened 2017-04-03 11:07 UTC

**Comment by c-w** [comment] 2017-05-11 23:58
This is currently implemented in [project-fortis-spark](https://github.com/CatalystCode/project-fortis-spark) via the [streaming-instagram](https://github.com/CatalystCode/streaming-instagram) library.

**Comment by c-w** [comment] 2017-05-12 21:19
This is a dupe of #38. Resolving.

**Closed by c-w** 2017-05-12 21:19 UTC
